In [ ]:
#what is numpy
#Numpy is a general-purpose array-processing package

#numpy
import numpy as np

my_lst =[1,2,3,4,5]
print(type(my_lst))

[1, 2, 3, 4, 5]


In [5]:
arr =np.array(my_lst)
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr.shape

(5,)

In [7]:
## Multinested array
my_lst1 = [1, 2, 3, 4, 5]
my_lst2 = [2, 3, 4, 5, 6]
my_lst3 = [9, 7, 6, 8, 9]

arr = np.array([my_lst1, my_lst2, my_lst3])
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
#number of elements must be same if we reshape it
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [11]:
#indexing

arrOne = np.array([1,2,3,4,5,6,7,8,9])

In [12]:
#indexing
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr[1,:]

array([2, 3, 4, 5, 6])

In [ ]:
#arr[r,c]
arr[0:,1]

array([2, 3, 7])

In [20]:
arr[1,0:2]

array([2, 3])

In [22]:
arrTwo = np.arange(0,10)
print(arrTwo)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
#random
## random distribution
np.random.rand(3,3)


array([[0.82929784, 0.3868546 , 0.36153636],
       [0.68033245, 0.25348589, 0.38101993],
       [0.31808936, 0.99063403, 0.12635872]])